version: '3.9'

services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exampleDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/exampleDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - .:/workspace
    command: ["sh", "-c", "cd /workspace && ./mvnw spring-boot:run"]

volumes:
  postgres_data:
