# Generated by Django 4.2.13 on 2024-05-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=5)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
